//! About command module root
//!
//! This module exposes the `about` subcommand and routes to the argument
//! definition and handler implementation. The command is purely informational
//! and prints author and contact information in a stylized manner.

/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public module 'args'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub mod args;
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public module 'handler'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub mod handler;

pub use args::*;
pub use handler::run;
