/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public module 'args'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub mod args;
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public module 'build_all'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub mod build_all;
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public module 'build_project'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub mod build_project;
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public module 'handler'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub mod handler;
mod hook_base_filter;
mod hook_command;
mod hook_env;
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public module 'hooks'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub mod hooks;
mod output;
mod package_filter;
mod package_module;
mod package_template;
mod shell_optimize;

pub use args::*;
pub use handler::run;
