/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public module 'args'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub mod args;
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public module 'handler'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub mod handler;
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public module 'impl_mod'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub mod impl_mod;
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public module 'interactive'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub mod interactive;
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public module 'post_init'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub mod post_init;
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public module 'pre_init'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub mod pre_init;

pub use args::*;
pub use handler::run;
