/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public module 'args'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub mod args;
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public module 'cert'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub mod cert;
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public module 'file'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub mod file;
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public module 'github'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub mod github;
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public module 'handler'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub mod handler;
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public module 'index'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub mod index;
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public module 'utils'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub mod utils;
pub use args::*;
pub use handler::run;
pub use index::{SecretIndex, SecretMeta};
pub use utils::{global_with_backup_default, read_secret_blob, read_secret_plaintext};
