// Declare submodules
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public module 'build'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub mod build;

/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public module 'kam'. Replace with real documentation. (2025-12-30T22:23:21Z)

pub mod kam;
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public module 'manager'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub mod manager;
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public module 'mmrl'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub mod mmrl;
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public module 'note'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub mod note;
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public module 'options'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub mod options;
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public module 'prop'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub mod prop;
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public module 'repo'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub mod repo;
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public module 'tmpl'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub mod tmpl;
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public module 'tool'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub mod tool;
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public module 'workspace'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub mod workspace;

// Re-export main types
pub use crate::types::kam_toml::enums::{ModuleType, SupportedArch};
pub use build::BuildSection;

pub use kam::KamSection;
pub use manager::ManagerSection;
pub use mmrl::MmrlSection;
pub use note::NoteSection;
pub use options::OptionsSection;
pub use prop::PropSection;
pub use repo::RepoSection;
pub use tmpl::{TmplSection, VariableDefinition};
pub use tool::ToolSection;
pub use workspace::WorkspaceSection;
