[[base]]
name = "anykernel3"
path = "src/AnyKernel3"
url = "https://github.com/osm0sis/AnyKernel3.git"
branch = "master"
kind = "submodule"

[[base]]
name = "hooks"
path = ".kam/bases/hooks"
url = "https://github.com/MemDeco-WG/KamHooks.git"
branch = "main"
kind = "submodule"
include = [
  "pre-build/1000.SYNC_MODULE_FILES.sh",
  "post-build/7000.SANITIZE_MODULE_ZIP.sh",
  "post-build/8000.SIGN_IF_ENABLE.sh",
  "post-build/8900.UPDATE_CHANGE_LOG.sh",
  "post-build/9000.UPLOAD_IF_ENABLED.sh",
  "post-build/9800.INTERACTIVE_INSTALL.sh",
  "post-build/9900.CLEAN_UP.sh",
]

[[base]]
name = "workflows"
path = ".kam/bases/workflows"
url = "https://github.com/MemDeco-WG/KamModuleX.git"
branch = "main"
kind = "submodule"
subdir = ".github/workflows"
overlay = ".github/workflows"
include = ["README-CN.md", "README.md", "exec.yml", "init.yml"]
