[prop]
id = "Kam"
name = "Kam"
version = "v0.5.13"
versionCode = 1766742680815
author = "LightJunction"
description = "This is a Example Module！ Do not install it!"
updateJson = "https://raw.githubusercontent.com/MemDeco-WG/Kam/main/update.json"
metamodule = false

[mmrl.repo]
license = "MIT"
license_file = "LICENSE"
homepage = "https://github.com/MemDeco-WG/Kam"
readme = "https://github.com/MemDeco-WG/Kam/blob/main/README.md"
readme_file = "README.md"
changelog = "https://github.com/MemDeco-WG/Kam/blob/main/CHANGELOG.md"
changelog_file = "CHANGELOG.md"
screenshots = []
categories = ["tools"]
keywords = [
    "kam",
    "module",
    "android",
    "template",
]
maintainers = ["LightJunction"]
repository = "https://github.com/MemDeco-WG/Kam"
documentation = "https://github.com/MemDeco-WG/Kam"
issues = "https://github.com/MemDeco-WG/Kam/issues"
funding = "https://github.com/sponsors/LightJunction"
support = "https://github.com/MemDeco-WG/Kam/issues"
donate = ""
cover = ""
icon = ""
devices = []
arch = ["arm64-v8a"]
require = []
antifeatures = []
max_num = 0
min_api = 21
max_api = 35
verified = true
features = [
    "module-template",
    "customization",
]

[mmrl.repo.note]
title = ""
message = ""

[mmrl.repo.manager.magisk]
devices = []
arch = []
require = []

[mmrl.repo.manager.kernelsu]
devices = []
arch = []
require = []

[mmrl.repo.manager.apatch]
devices = []
arch = []
require = []

[mmrl.repo.options.archive]
compression = ""

[kam]
min_api = 0
max_api = 0
supported_arch = ["arm64"]
conflicts = []
module_type = "kam"

[kam.build]
source_dir = "src/Kam"
target_dir = "dist"
output_file = "{{id}}"
hooks_dir = "hooks"

[kam.tmpl.variables.repository]
var_type = "string"
required = false
default = ""

[kam.workspace]
members = [
    "[tmpl/*_template]",
    ".",
]

[tool]
