[kam]
conflicts = []
max_api = 0
min_api = 0
module_type = "kam"
supported_arch = ["arm64"]

[kam.build]
hooks_dir = "hooks"
output_file = "{{id}}"
source_dir = "src/Kam"
target_dir = "dist"

[kam.tmpl.variables.repository]
default = ""
required = false
var_type = "string"

[kam.workspace]
members = [
    "[tmpl/*_template]",
    ".",
]

[mmrl.repo]
antifeatures = []
arch = ["arm64-v8a"]
categories = ["tools"]
changelog = "https://github.com/MemDeco-WG/Kam/blob/main/CHANGELOG.md"
changelog_file = "CHANGELOG.md"
cover = ""
devices = []
documentation = "https://github.com/MemDeco-WG/Kam"
donate = ""
features = [
    "module-template",
    "customization",
]
funding = "https://github.com/sponsors/LightJunction"
homepage = "https://github.com/MemDeco-WG/Kam"
icon = ""
issues = "https://github.com/MemDeco-WG/Kam/issues"
keywords = [
    "kam",
    "module",
    "android",
    "template",
]
license = "MIT"
license_file = "LICENSE"
maintainers = ["LightJunction"]
max_api = 35
max_num = 0
min_api = 21
readme = "https://github.com/MemDeco-WG/Kam/blob/main/README.md"
readme_file = "README.md"
repository = "https://github.com/MemDeco-WG/Kam"
require = []
screenshots = []
support = "https://github.com/MemDeco-WG/Kam/issues"
verified = true

[mmrl.repo.manager.apatch]
arch = []
devices = []
require = []

[mmrl.repo.manager.kernelsu]
arch = []
devices = []
require = []

[mmrl.repo.manager.magisk]
arch = []
devices = []
require = []

[mmrl.repo.note]
message = ""
title = ""

[mmrl.repo.options.archive]
compression = ""

[prop]
author = "LightJunction"
description = "Kam — A CLI toolkit for scaffolding, building, and distributing ksu/APU/Magisk/AnyTemplate modules"
id = "Kam"
metamodule = false
name = "Kam"
updateJson = "https://raw.githubusercontent.com/MemDeco-WG/Kam/main/update.json"
version = "v0.4.37"
versionCode = 1765728172521

[tool]
