use crate::types::kam_toml::KamToml;
use std::fmt::Write;

fn kernelsu_summary(input: &str) -> String {
    let trimmed = input.trim();
    if trimmed.chars().count() <= 512 {
        return trimmed.to_string();
    }
    trimmed.chars().take(512).collect()
}

fn optional_json_string(value: String) -> serde_json::Value {
    if value.trim().is_empty() {
        serde_json::Value::Null
    } else {
        serde_json::Value::String(value)
    }
}

// 构建module.prop文件内容
// 就是简单的key=value格式，一行一行拼起来
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public function 'build_prop'. Replace with real documentation. (2025-12-30T22:23:21Z)
#[must_use]
pub fn build_prop(kt: &KamToml) -> String {
    let mut content = String::new();
    let _ = writeln!(content, "id={}", kt.prop.id);
    let _ = writeln!(content, "name={}", kt.prop.name);
    let _ = writeln!(content, "version={}", kt.prop.version);
    let _ = writeln!(content, "versionCode={}", kt.prop.versionCode);
    // author是可选的，有的话才写
    if let Some(author) = &kt.prop.author {
        let _ = writeln!(content, "author={author}");
    }
    let _ = writeln!(content, "description={}", kt.prop.description);
    if let Some(uj) = &kt.prop.updateJson {
        let _ = writeln!(content, "updateJson={uj}");
    }
    content
}

// 构建module.json内容（MMRL格式）
// 这个函数有点复杂，主要是处理各种可选字段和嵌套结构
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public function 'build_module_json'. Replace with real documentation. (2025-12-30T22:23:21Z)
#[must_use]
pub fn build_module_json(kt: &KamToml) -> serde_json::Value {
    let metamodule = kt.prop.metamodule;
    let summary = kernelsu_summary(&kt.prop.description);
    // 优先用repository，没有就用homepage，都没有就空字符串
    let source_url = kt
        .mmrl
        .as_ref()
        .and_then(|m| m.repo.as_ref())
        .and_then(|r| r.repository.clone())
        .or_else(|| {
            kt.mmrl
                .as_ref()
                .and_then(|m| m.repo.as_ref())
                .and_then(|r| r.homepage.clone())
        })
        .unwrap_or_default();

    // 收集作者列表，从prop.author和mmrl.repo.maintainers里找
    let mut authors: Vec<serde_json::Value> = vec![];
    if let Some(author) = &kt.prop.author
        && !author.trim().is_empty()
    {
        let mut author_obj = serde_json::Map::new();
        author_obj.insert(
            "type".to_string(),
            serde_json::Value::String("add".to_string()),
        );
        author_obj.insert(
            "name".to_string(),
            serde_json::Value::String(author.clone()),
        );
        authors.push(serde_json::Value::Object(author_obj));
    }
    // 从mmrl.repo.maintainers里也收集作者
    // maintainers可以是字符串或对象，需要分别处理
    if let Some(mmrl) = &kt.mmrl
        && let Some(repo) = &mmrl.repo
        && let Some(maintainers) = &repo.maintainers
    {
        for maint in maintainers {
            match maint {
                crate::types::kam_toml::sections::repo::MaintainerEntry::Name(s) => {
                    // 简单字符串格式，直接转成对象
                    let mut obj = serde_json::Map::new();
                    obj.insert(
                        "type".to_string(),
                        serde_json::Value::String("add".to_string()),
                    );
                    obj.insert("name".to_string(), serde_json::Value::String(s.clone()));
                    authors.push(serde_json::Value::Object(obj));
                }
                crate::types::kam_toml::sections::repo::MaintainerEntry::Object(m) => {
                    // 对象格式，可能有type、name、link等字段
                    let mut obj = serde_json::Map::new();
                    let t = m.r#type.clone().unwrap_or_else(|| "add".to_string());
                    obj.insert("type".to_string(), serde_json::Value::String(t));
                    obj.insert(
                        "name".to_string(),
                        serde_json::Value::String(m.name.clone()),
                    );
                    if let Some(link) = &m.link {
                        obj.insert("link".to_string(), serde_json::Value::String(link.clone()));
                    }
                    authors.push(serde_json::Value::Object(obj));
                }
            }
        }
    }

    let mut root = serde_json::Map::new();
    root.insert(
        "metamodule".to_string(),
        serde_json::Value::Bool(metamodule),
    );
    root.insert("summary".to_string(), serde_json::Value::String(summary));
    root.insert("sourceUrl".to_string(), optional_json_string(source_url));
    root.insert(
        "additionalAuthors".to_string(),
        serde_json::Value::Array(authors),
    );
    serde_json::Value::Object(root)
}

// 构建update.json内容
// 包含版本、下载链接、changelog等
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public function 'build_update_json'. Replace with real documentation. (2025-12-30T22:23:21Z)
#[must_use]
pub fn build_update_json(kt: &KamToml) -> serde_json::Value {
    let version = kt.prop.version.clone();
    let version_code = kt.prop.versionCode;

    // 获取仓库URL（优先repository，没有就用homepage）
    let repo_url = kt
        .mmrl
        .as_ref()
        .and_then(|m| m.repo.as_ref())
        .and_then(|r| r.repository.clone())
        .or_else(|| {
            kt.mmrl
                .as_ref()
                .and_then(|m| m.repo.as_ref())
                .and_then(|r| r.homepage.clone())
        })
        .unwrap_or_default();

    // 构建zip下载URL
    // 如果是GitHub就按GitHub的格式，否则用通用格式
    // 都没有就用默认的占位符URL
    let zip_url = if repo_url.contains("github.com") {
        format!(
            "{}/releases/latest/download/{}.zip",
            repo_url.trim_end_matches('/'),
            kt.prop.id
        )
    } else if !repo_url.is_empty() {
        // 非GitHub仓库，也用类似的格式（虽然可能不太对）
        format!(
            "{}/releases/latest/download/{}.zip",
            repo_url.trim_end_matches('/'),
            kt.prop.id
        )
    } else {
        // 没有仓库URL，用默认占位符
        format!(
            "https://github.com/user/repo/releases/latest/download/{}.zip",
            kt.prop.id
        )
    };

    // 构建changelog URL
    // 优先用配置的changelog，没有就根据仓库URL推断
    let changelog = kt
        .mmrl
        .as_ref()
        .and_then(|m| m.repo.as_ref())
        .and_then(|r| r.changelog.clone())
        .or_else(|| {
            if !repo_url.is_empty() && repo_url.contains("github.com") {
                // GitHub仓库，用raw.githubusercontent.com
                Some(format!(
                    "{}/raw/main/CHANGELOG.md",
                    repo_url.trim_end_matches('/')
                ))
            } else if !repo_url.is_empty() {
                // 其他仓库，直接拼接CHANGELOG.md
                Some(format!("{}/CHANGELOG.md", repo_url.trim_end_matches('/')))
            } else {
                // 都没有，用默认占位符
                Some("https://raw.githubusercontent.com/user/repo/main/CHANGELOG.md".to_string())
            }
        })
        .unwrap_or_default();

    let mut root = serde_json::Map::new();
    root.insert("version".to_string(), serde_json::Value::String(version));
    root.insert("versionCode".to_string(), serde_json::json!(version_code));
    root.insert("zipUrl".to_string(), serde_json::Value::String(zip_url));
    root.insert(
        "changelog".to_string(),
        serde_json::Value::String(changelog),
    );
    serde_json::Value::Object(root)
}

// 构建repo.json内容（MMRL仓库格式）
// 这个函数也很长，主要是把kam.toml的mmrl.repo字段转成JSON
// TODO: split this function into smaller units to address clippy::too_many_lines
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public function 'build_repo_json'. Replace with real documentation. (2025-12-30T22:23:21Z)
#[allow(clippy::too_many_lines)]
#[must_use]
pub fn build_repo_json(kt: &KamToml) -> serde_json::Value {
    let mut root = serde_json::Map::new();

    // 如果有mmrl配置，就提取相关字段
    if let Some(mmrl) = &kt.mmrl
        && let Some(repo) = &mmrl.repo
    {
        // license字段
        if let Some(license) = &repo.license
            && !license.is_empty()
        {
            root.insert(
                "license".to_string(),
                serde_json::Value::String(license.clone()),
            );
        }

        if let Some(home) = &repo.homepage
            && !home.is_empty()
        {
            root.insert(
                "homepage".to_string(),
                serde_json::Value::String(home.clone()),
            );
        }

        if let Some(readme) = &repo.readme
            && !readme.is_empty()
        {
            root.insert(
                "readme".to_string(),
                serde_json::Value::String(readme.clone()),
            );
        }

        if let Some(screens) = &repo.screenshots {
            root.insert(
                "screenshots".to_string(),
                serde_json::Value::Array(
                    screens
                        .iter()
                        .map(|s| serde_json::Value::String(s.clone()))
                        .collect(),
                ),
            );
        }

        if let Some(categories) = &repo.categories {
            root.insert(
                "categories".to_string(),
                serde_json::Value::Array(
                    categories
                        .iter()
                        .map(|s| serde_json::Value::String(s.clone()))
                        .collect(),
                ),
            );
        }

        if let Some(devices) = &repo.devices {
            root.insert(
                "devices".to_string(),
                serde_json::Value::Array(
                    devices
                        .iter()
                        .map(|s| serde_json::Value::String(s.clone()))
                        .collect(),
                ),
            );
        }

        if let Some(arch) = &repo.arch {
            root.insert(
                "arch".to_string(),
                serde_json::Value::Array(
                    arch.iter()
                        .map(|s| serde_json::Value::String(s.clone()))
                        .collect(),
                ),
            );
        }

        if let Some(require) = &repo.require {
            root.insert(
                "require".to_string(),
                serde_json::Value::Array(
                    require
                        .iter()
                        .map(|s| serde_json::Value::String(s.clone()))
                        .collect(),
                ),
            );
        }

        if let Some(donate) = &repo.donate
            && !donate.is_empty()
        {
            root.insert(
                "donate".to_string(),
                serde_json::Value::String(donate.clone()),
            );
        }

        if let Some(support) = &repo.support
            && !support.is_empty()
        {
            root.insert(
                "support".to_string(),
                serde_json::Value::String(support.clone()),
            );
        }

        if let Some(cover) = &repo.cover
            && !cover.is_empty()
        {
            root.insert(
                "cover".to_string(),
                serde_json::Value::String(cover.clone()),
            );
        }

        if let Some(icon) = &repo.icon
            && !icon.is_empty()
        {
            root.insert("icon".to_string(), serde_json::Value::String(icon.clone()));
        }

        // maintainers字段：支持字符串或对象格式
        if let Some(maintainers) = &repo.maintainers {
            let mut arr: Vec<serde_json::Value> = vec![];
            for maint in maintainers {
                match maint {
                    crate::types::kam_toml::sections::repo::MaintainerEntry::Name(s) => {
                        // 简单字符串格式，转成对象
                        let mut obj = serde_json::Map::new();
                        obj.insert(
                            "type".to_string(),
                            serde_json::Value::String("add".to_string()),
                        );
                        obj.insert("name".to_string(), serde_json::Value::String(s.clone()));
                        arr.push(serde_json::Value::Object(obj));
                    }
                    crate::types::kam_toml::sections::repo::MaintainerEntry::Object(m) => {
                        // 对象格式，可能有type、name、link等字段
                        let mut obj = serde_json::Map::new();
                        let t = m.r#type.clone().unwrap_or_else(|| "add".to_string());
                        obj.insert("type".to_string(), serde_json::Value::String(t));
                        obj.insert(
                            "name".to_string(),
                            serde_json::Value::String(m.name.clone()),
                        );
                        if let Some(link) = &m.link {
                            obj.insert("link".to_string(), serde_json::Value::String(link.clone()));
                        }
                        arr.push(serde_json::Value::Object(obj));
                    }
                }
            }
            root.insert("maintainers".to_string(), serde_json::Value::Array(arr));
        }

        if let Some(note) = &repo.note
            && let Ok(v) = serde_json::to_value(note)
        {
            root.insert("note".to_string(), v);
        }

        if let Some(manager) = &repo.manager
            && let Ok(v) = serde_json::to_value(manager)
        {
            root.insert("manager".to_string(), v);
        }
    }
    serde_json::Value::Object(root)
}

// 构建track.json内容
// 这个格式可能不太常用，但留着总没错
