use super::repo::RepoSection;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq)]
#[allow(non_snake_case)]
// MMRL顶层节：包含仓库/发布相关的子配置
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public struct 'MmrlSection'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub struct MmrlSection {
    // 仓库相关元数据，包含许可、主页、屏幕截图等信息
    /// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public field 'repo' in 'MmrlSection'. Replace with real documentation. (2025-12-30T22:23:21Z)
    pub repo: Option<RepoSection>,
}

impl Default for MmrlSection {
    fn default() -> Self {
        Self {
            repo: Some(RepoSection::default()),
        }
    }
}
