use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq)]
#[allow(non_snake_case)]
// 提示/通知结构（MMRL V4+不支持color字段）
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public struct 'NoteSection'. Replace with real documentation. (2025-12-30T22:23:21Z)
#[derive(Default)]
pub struct NoteSection {
    // 通知标题
    /// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public field 'title' in 'NoteSection'. Replace with real documentation. (2025-12-30T22:23:21Z)
    pub title: String,
    // 通知正文/消息
    /// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public field 'message' in 'NoteSection'. Replace with real documentation. (2025-12-30T22:23:21Z)
    pub message: String,
}
