use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq)]
#[allow(non_snake_case)]
// 工具配置节，用于自定义工具配置
// 目前用JSON值存储，以后可能需要扩展
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public struct 'ToolSection'. Replace with real documentation. (2025-12-30T22:23:21Z)
#[derive(Default)]
pub struct ToolSection {
    // 暂时用JSON值存储，需要时再扩展
    /// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public field 'data' in 'ToolSection'. Replace with real documentation. (2025-12-30T22:23:21Z)
    pub data: Option<serde_json::Value>,
}
