use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq)]
#[allow(non_snake_case)]
// 工作区配置节，用于Kam工作区管理，类似Cargo的workspaces
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public struct 'WorkspaceSection'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub struct WorkspaceSection {
    // 工作区成员列表（相对于工作区根的路径）
    /// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public field 'members' in 'WorkspaceSection'. Replace with real documentation. (2025-12-30T22:23:21Z)
    pub members: Option<Vec<String>>,
    // 要从工作区排除的路径列表
    /// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public field 'exclude' in 'WorkspaceSection'. Replace with real documentation. (2025-12-30T22:23:21Z)
    pub exclude: Option<Vec<String>>,
}

impl Default for WorkspaceSection {
    fn default() -> Self {
        Self {
            members: Some(vec![".".to_string()]),
            exclude: None,
        }
    }
}
