use thiserror::Error;

/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public enum 'KamTomlError'. Replace with real documentation. (2025-12-30T22:23:21Z)
#[derive(Debug, Error)]
pub enum KamTomlError {
    #[error("TOML syntax error: {0}")]
    /// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public enum variant 'TomlSyntax' in 'KamTomlError'. Replace with real documentation. (2025-12-30T22:23:21Z)
    TomlSyntax(#[from] toml_edit::TomlError),
    #[error("TOML schema error: {0}")]
    /// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public enum variant 'TomlSchema' in 'KamTomlError'. Replace with real documentation. (2025-12-30T22:23:21Z)
    TomlSchema(#[from] toml_edit::de::Error),
    #[error("TOML deserialization error: {0}")]
    /// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public enum variant 'TomlDe' in 'KamTomlError'. Replace with real documentation. (2025-12-30T22:23:21Z)
    TomlDe(#[from] toml::de::Error),
    #[error("TOML serialization error: {0}")]
    /// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public enum variant 'TomlSer' in 'KamTomlError'. Replace with real documentation. (2025-12-30T22:23:21Z)
    TomlSer(#[from] toml::ser::Error),
    #[error("IO error: {0}")]
    /// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public enum variant 'Io' in 'KamTomlError'. Replace with real documentation. (2025-12-30T22:23:21Z)
    Io(#[from] std::io::Error),
    #[error("kam.toml not found at {0}")]
    /// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public enum variant 'NotFound' in 'KamTomlError'. Replace with real documentation. (2025-12-30T22:23:21Z)
    NotFound(String),
    #[error("kam.toml is empty")]
    /// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public enum variant 'EmptyFile' in 'KamTomlError'. Replace with real documentation. (2025-12-30T22:23:21Z)
    EmptyFile,
    #[error("Missing required field: id")]
    /// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public enum variant 'MissingId' in 'KamTomlError'. Replace with real documentation. (2025-12-30T22:23:21Z)
    MissingId,
    #[error("Missing required field: name")]
    /// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public enum variant 'MissingName' in 'KamTomlError'. Replace with real documentation. (2025-12-30T22:23:21Z)
    MissingName,
    #[error("Missing required field: version")]
    /// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public enum variant 'MissingVersion' in 'KamTomlError'. Replace with real documentation. (2025-12-30T22:23:21Z)
    MissingVersion,
    #[error("Missing required field: description")]
    /// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public enum variant 'MissingDescription' in 'KamTomlError'. Replace with real documentation. (2025-12-30T22:23:21Z)
    MissingDescription,
    #[error("Invalid id: {0}")]
    /// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public enum variant 'InvalidId' in 'KamTomlError'. Replace with real documentation. (2025-12-30T22:23:21Z)
    InvalidId(String),
    #[error("Version must be in format x.y.z")]
    /// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public enum variant 'InvalidVersionFormat' in 'KamTomlError'. Replace with real documentation. (2025-12-30T22:23:21Z)
    InvalidVersionFormat,
    #[error("License file not found: {0}")]
    /// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public enum variant 'LicenseNotFound' in 'KamTomlError'. Replace with real documentation. (2025-12-30T22:23:21Z)
    LicenseNotFound(String),
    #[error("License file is empty: {0}")]
    /// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public enum variant 'LicenseEmpty' in 'KamTomlError'. Replace with real documentation. (2025-12-30T22:23:21Z)
    LicenseEmpty(String),
    #[error("Readme file not found: {0}")]
    /// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public enum variant 'ReadmeNotFound' in 'KamTomlError'. Replace with real documentation. (2025-12-30T22:23:21Z)
    ReadmeNotFound(String),
    #[error("Readme file is empty: {0}")]
    /// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public enum variant 'ReadmeEmpty' in 'KamTomlError'. Replace with real documentation. (2025-12-30T22:23:21Z)
    ReadmeEmpty(String),
    #[error("Changelog file not found: {0}")]
    /// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public enum variant 'ChangelogNotFound' in 'KamTomlError'. Replace with real documentation. (2025-12-30T22:23:21Z)
    ChangelogNotFound(String),
    #[error("Changelog file is empty: {0}")]
    /// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public enum variant 'ChangelogEmpty' in 'KamTomlError'. Replace with real documentation. (2025-12-30T22:23:21Z)
    ChangelogEmpty(String),
    #[error("Unsupported architecture: {0}, supported: {1:?}")]
    /// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public enum variant 'UnsupportedArch' in 'KamTomlError'. Replace with real documentation. (2025-12-30T22:23:21Z)
    UnsupportedArch(String, Vec<String>),
    #[error("Template module missing [kam.tmpl] section")]
    /// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public enum variant 'TemplateMissingTmpl' in 'KamTomlError'. Replace with real documentation. (2025-12-30T22:23:21Z)
    TemplateMissingTmpl,
    #[error("Duplicate key in unique map: {0}")]
    /// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public enum variant 'DuplicateKey' in 'KamTomlError'. Replace with real documentation. (2025-12-30T22:23:21Z)
    DuplicateKey(String),
}

/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public enum 'ValidationResult'. Replace with real documentation. (2025-12-30T22:23:21Z)
#[derive(Debug, PartialEq, Eq)]
pub enum ValidationResult {
    /// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public enum variant 'Valid' in 'ValidationResult'. Replace with real documentation. (2025-12-30T22:23:21Z)
    Valid,
    /// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public enum variant 'Invalid' in 'ValidationResult'. Replace with real documentation. (2025-12-30T22:23:21Z)
    Invalid(String),
}
