use std::path::Path;

use crate::errors::KamError;

/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public function 'post_process'. Replace with real documentation. (2025-12-30T22:23:21Z)

pub fn post_process(path: &Path) -> Result<(), KamError> {
    // Template variable validation is handled by the template engine and `init_template`.
    // Folders
    use crate::utils::Utils;
    Utils::success(format!("Initialized Kam project in {}", path.display()));

    Ok(())
}
