use clap::Args;

/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public struct 'ValidateArgs'. Replace with real documentation. (2025-12-30T22:23:21Z)
#[derive(Args)]
pub struct ValidateArgs {
    /// Path to the project directory (default: current directory)
    #[arg(default_value = ".")]
    pub path: String,
}
