use clap::Args;
use std::path::PathBuf;

/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public struct 'ExportArgs'. Replace with real documentation. (2025-12-30T22:23:21Z)
#[derive(Args, Debug)]
pub struct ExportArgs {
    /// Export format: prop, json, update, repo, track, config
    #[arg(value_enum)]
    pub format: Option<ExportFormat>,
    /// Output file path (default: write to a format-specific filename in the current directory)
    pub output: Option<PathBuf>,
}

/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public enum 'ExportFormat'. Replace with real documentation. (2025-12-30T22:23:21Z)
#[derive(clap::ValueEnum, Clone, Debug)]
pub enum ExportFormat {
    /// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public enum variant 'Prop' in 'ExportFormat'. Replace with real documentation. (2025-12-30T22:23:21Z)
    Prop,
    /// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public enum variant 'Json' in 'ExportFormat'. Replace with real documentation. (2025-12-30T22:23:21Z)
    Json,
    /// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public enum variant 'Repo' in 'ExportFormat'. Replace with real documentation. (2025-12-30T22:23:21Z)
    Repo,
    /// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public enum variant 'Track' in 'ExportFormat'. Replace with real documentation. (2025-12-30T22:23:21Z)
    Track,
    /// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public enum variant 'Config' in 'ExportFormat'. Replace with real documentation. (2025-12-30T22:23:21Z)
    Config,
    /// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public enum variant 'Update' in 'ExportFormat'. Replace with real documentation. (2025-12-30T22:23:21Z)
    Update,
}
