use rust_embed::RustEmbed;

/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public struct 'TmplAssets'. Replace with real documentation. (2025-12-30T22:23:21Z)
#[derive(RustEmbed)]
#[folder = "src/assets/tmpl"]
pub struct TmplAssets;
