/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public module 'tmpl'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub mod tmpl;

use rust_embed::RustEmbed;
pub use tmpl::TmplAssets;

/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public struct 'Assets'. Replace with real documentation. (2025-12-30T22:23:21Z)
#[derive(RustEmbed)]
#[folder = "src/assets/"]
pub struct Assets;
