use clap::{CommandFactory, FromArgMatches, Parser, Subcommand};
use std::collections::HashSet;
use std::ffi::OsString;

#[derive(Parser)]
#[command(
    name = "kam",
    about = "A CLI toolkit for scaffolding, building, and distributing ksu/APU/Magisk/AnyTemplate modules",
    long_about = "A CLI toolkit for scaffolding, building, packaging, and distributing Android modules and templates (ksu/APU/Magisk/AnyTemplate). It supports module initialization, packaging, template management, and repo metadata exports.",
    version,
    disable_help_subcommand = true,
    help_template = "{bin} — {about}\n\nUsage: {usage}\n\nCommands:\n{subcommands}\n\n{after-help}\n"
)]
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public struct 'Cli'. Replace with real documentation. (2025-12-30T22:23:21Z)
#[allow(clippy::struct_excessive_bools)]
pub struct Cli {
    /// Pacman-style sync (download) flag (equivalent to pacman -S)
    #[arg(short = 'S', action = clap::ArgAction::SetTrue)]
    pub sync_flag: bool,

    /// Pacman-style search modifier (use with -S as '-Ss' to search or '-s' alone to search)
    #[arg(short = 's', long = "search", action = clap::ArgAction::SetTrue)]
    pub search_flag: bool,

    /// Positional targets: module IDs or search terms (used with -S / -s)
    #[arg(value_name = "TARGETS", num_args = 0.., last = true)]
    pub targets: Vec<String>,

    /// URL for the modules registry API (default: <https://modules.kernelsu.org>). Overrides the built-in modules endpoint.
    #[arg(long = "modules-url", value_name = "URL", global = true)]
    pub modules_url: Option<String>,

    /// Assume "yes" to all confirmation prompts (equivalent to -y). Use `-y` or `--yes` to skip confirmation.
    #[arg(short = 'y', long = "yes", action = clap::ArgAction::SetTrue, global = true)]
    pub assume_yes: bool,

    /// Suppress progress/output (quiet mode). Useful with pacman-style syncs (-S) to avoid progress bars in CI.
    #[arg(short = 'q', long = "quiet", action = clap::ArgAction::SetTrue, global = true)]
    pub quiet: bool,

    /// Update (refresh) the modules registry index before sync/download (equivalent to `kam repo sync --force`). Use `-u` or `--update` to enable.
    #[arg(short = 'u', long = "update", action = clap::ArgAction::SetTrue, global = true)]
    pub update_index: bool,

    #[command(subcommand)]
    /// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public field 'command' in 'Cli'. Replace with real documentation. (2025-12-30T22:23:21Z)
    pub command: Option<Commands>,
}

/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public enum 'Commands'. Replace with real documentation. (2025-12-30T22:23:21Z)
#[derive(Subcommand)]
pub enum Commands {
    /// Initialize a new Kam project from templates (supports meta and kernel templates)
    Init(crate::cmds::init::InitArgs),

    /// Build and package a module into a deployable ZIP artifact
    Build(crate::cmds::build::BuildArgs),

    /// Manage module versions and bump policies
    Version(crate::cmds::version::VersionArgs),

    /// Manage module versions and bump policies
    Cache(crate::cmds::cache::CacheArgs),

    /// Manage templates: import, export, package, and list
    Tmpl(crate::cmds::tmpl::TmplArgs),

    /// Validate `kam.toml` configuration and templates
    Validate(crate::cmds::validate::ValidateArgs),

    /// Generate shell completion scripts for common shells
    Completions(crate::cmds::completion::CompletionArgs),

    /// Secret keyring management (used by sign/verify tasks)
    Secret(crate::cmds::secret::SecretArgs),

    /// Sign an artifact using a key from the keyring or a PEM file
    Sign(crate::cmds::sign::SignArgs),
    /// Verify an artifact signature (.sig) or a sigstore bundle (DSSE)
    Verify(crate::cmds::verify::VerifyArgs),

    /// Check project JSON/YAML/Markdown files (lint/format/parse)
    Check(crate::cmds::check::CheckArgs),

    /// Export `kam.toml` to `module.prop`, `module.json`, `repo.json`, `track.json`, `config.json`, `update.json`
    Export(crate::cmds::export::ExportArgs),

    /// Inspect and edit `kam.toml` using dot-path keys (get/set/unset/list)
    Toml(crate::cmds::toml::TomlArgs),

    /// Manage per-project or global kam configuration (similar to git config)
    Config(crate::cmds::config::ConfigArgs),

    /// Act as a compatibility layer for Magisk, `KernelSU`, and `APatchSU` to install modules (delegates to configured root manager)
    Install(crate::cmds::install::InstallArgs),

    /// Interact with module repository (search/download)
    Repo(crate::cmds::repo::RepoArgs),

    /// Display about information for Kam and credits
    About(crate::cmds::about::AboutArgs),

    /// Print environment variables starting with KAM_ (for debugging)
    Env(crate::cmds::env::EnvArgs),

    /// Print this message or the help of the given subcommand(s)
    Help(crate::cmds::help::HelpArgs),
}

impl Cli {
    /// Parse an argv-like iterator while supporting pacman-style short-flag combinations
    /// (e.g. `-Syu`) by injecting a `--` before positional `TARGETS` when appropriate.
    ///
    /// Accepts any iterator over items that can be borrowed as an `OsStr` (so `&str`,
    /// `String`, `OsString`, etc. all work). Returns a `Result<Cli, clap::Error>`
    /// mirroring clap's `try_parse_from` semantics.
    ///
    /// # Errors
    /// Returns a `clap::Error` when parsing fails.
    pub fn try_parse_from_with_pacman<I, T>(args: I) -> Result<Self, clap::Error>
    where
        I: IntoIterator<Item = T>,
        T: AsRef<std::ffi::OsStr>,
    {
        // Collect into OsString for manipulation
        let mut args_os: Vec<OsString> = args
            .into_iter()
            .map(|t| t.as_ref().to_os_string())
            .collect();

        // If the user already supplied `--` we don't touch the args.
        if args_os.iter().any(|a| a == &OsString::from("--")) {
            let matches = Self::command().try_get_matches_from(args_os)?;
            return Self::from_arg_matches(&matches);
        }

        // Collect subcommand names so we don't mistakenly insert `--` before a real subcommand.
        let sub_names: HashSet<String> = Self::command()
            .get_subcommands()
            .map(|s| s.get_name().to_string())
            .collect();

        // Look for tokens that are either explicit sync/search tokens or combined short flags
        // containing 'S' or 's' (e.g., `-Syu`, `-yuS`, `-Ss`) and insert `--` before the next
        // non-option/non-subcommand token so positional `TARGETS` are parsed correctly.
        for i in 1..args_os.len() {
            if let Some(tok) = args_os[i].to_str() {
                // Exact matches we historically supported.
                let explicit =
                    tok == "-S" || tok == "-s" || tok == "-Ss" || tok == "-sS" || tok == "--search";

                // Detect combined short flags like `-Syu` or `-yuS`. We only accept letters
                // from the known set to avoid surprising behavior with unrelated flags.
                let combined = if tok.starts_with('-') && !tok.starts_with("--") {
                    let rest = &tok[1..];
                    let mut all_known = true;
                    let mut contains_sync_or_search = false;
                    for ch in rest.chars() {
                        match ch {
                            'S' | 's' => contains_sync_or_search = true,
                            'y' | 'u' | 'q' => {}
                            _ => {
                                all_known = false;
                                break;
                            }
                        }
                    }
                    all_known && contains_sync_or_search
                } else {
                    false
                };

                if (explicit || combined)
                    && i + 1 < args_os.len()
                    && let Some(next) = args_os[i + 1].to_str()
                    && !next.starts_with('-')
                    && !sub_names.contains(next)
                {
                    args_os.insert(i + 1, OsString::from("--"));
                    break;
                }
            }
        }

        // Parse using the derived Command (mirrors clap's default parsing path).
        let matches = Self::command().try_get_matches_from(args_os)?;
        Self::from_arg_matches(&matches)
    }

    /// Convenience wrapper that will exit the process on parse error (similar to clap's `parse_from` behavior).
    ///
    /// # Errors
    /// This function terminates the process with exit code 2 if argument parsing fails.
    pub fn parse_from_with_pacman<I, T>(args: I) -> Self
    where
        I: IntoIterator<Item = T>,
        T: AsRef<std::ffi::OsStr>,
    {
        match Self::try_parse_from_with_pacman(args) {
            Ok(v) => v,
            Err(e) => {
                eprintln!("Error parsing arguments: {e}");
                std::process::exit(2)
            }
        }
    }
}

/// Preprocess argv and insert `--` before pacman-style targets when appropriate.
///
/// This is a pure helper function that can be used by `main()` if it wants to
/// apply the same heuristic used by `Cli::try_parse_from_with_pacman`. It accepts
/// a mutable `Vec<OsString>` (as produced by `env::args_os().collect()`) and a
/// mutable reference to a `clap::Command` so it can consult subcommand names.
pub fn inject_double_dash_for_targets(
    mut args: Vec<std::ffi::OsString>,
    cmd: &mut clap::Command,
) -> Vec<std::ffi::OsString> {
    use std::collections::HashSet;

    // If the user already supplied `--` do nothing.
    if args.iter().any(|a| a == &std::ffi::OsString::from("--")) {
        return args;
    }

    // Known subcommand names to avoid inserting `--` before a real subcommand.
    let sub_names: HashSet<String> = cmd
        .get_subcommands()
        .map(|s| s.get_name().to_string())
        .collect();

    for i in 1..args.len() {
        if let Some(tok) = args[i].to_str() {
            let mut should_inject = false;

            // Exact matches (long or simple short forms)
            if tok == "-S" || tok == "-s" || tok == "-Ss" || tok == "-sS" || tok == "--search" {
                should_inject = true;
            } else if tok.starts_with('-') && !tok.starts_with("--") {
                // Potential combined short flags like `-Syu`, `-yuS`, `-Ss`.
                // Only treat as combined short flags if every character after '-'
                // is one of the known short options we support here (S, s, y, u, q).
                let mut all_known = true;
                let mut contains_sync_or_search = false;
                for ch in tok.chars().skip(1) {
                    match ch {
                        'S' | 's' => contains_sync_or_search = true,
                        'y' | 'u' | 'q' => {}
                        _ => {
                            all_known = false;
                            break;
                        }
                    }
                }
                if all_known && contains_sync_or_search {
                    should_inject = true;
                }
            }

            if should_inject
                && i + 1 < args.len()
                && let Some(next) = args[i + 1].to_str()
                && !next.starts_with('-')
                && !sub_names.contains(next)
            {
                args.insert(i + 1, std::ffi::OsString::from("--"));
                break;
            }
        }
    }

    args
}

#[cfg(test)]
mod tests {
    use super::{Cli, Commands, inject_double_dash_for_targets};
    use crate::cmds::secret::SecretCommands;
    use clap::CommandFactory;
    use std::ffi::OsString;

    fn os_args(args: &[&str]) -> Vec<OsString> {
        args.iter().map(OsString::from).collect()
    }

    fn parse(args: &[&str]) -> Cli {
        Cli::try_parse_from_with_pacman(args).expect("CLI args should parse")
    }

    #[test]
    fn inject_preserves_args_when_double_dash_already_exists() {
        let mut cmd = Cli::command();
        let args = os_args(&["kam", "-S", "--", "target"]);

        assert_eq!(inject_double_dash_for_targets(args.clone(), &mut cmd), args);
    }

    #[test]
    fn injects_after_explicit_sync_before_target() {
        let mut cmd = Cli::command();
        let args = inject_double_dash_for_targets(os_args(&["kam", "-S", "module"]), &mut cmd);

        assert_eq!(args, os_args(&["kam", "-S", "--", "module"]));
    }

    #[test]
    fn injects_after_long_search_before_target() {
        let mut cmd = Cli::command();
        let args =
            inject_double_dash_for_targets(os_args(&["kam", "--search", "module"]), &mut cmd);

        assert_eq!(args, os_args(&["kam", "--search", "--", "module"]));
    }

    #[test]
    fn injects_after_combined_pacman_flags_before_target() {
        let mut cmd = Cli::command();
        let args = inject_double_dash_for_targets(os_args(&["kam", "-yuS", "module"]), &mut cmd);

        assert_eq!(args, os_args(&["kam", "-yuS", "--", "module"]));
    }

    #[test]
    fn does_not_inject_for_unknown_short_flag() {
        let mut cmd = Cli::command();
        let args = os_args(&["kam", "-Sz", "module"]);

        assert_eq!(inject_double_dash_for_targets(args.clone(), &mut cmd), args);
    }

    #[test]
    fn does_not_inject_before_subcommand_name() {
        let mut cmd = Cli::command();
        let args = os_args(&["kam", "-S", "build"]);

        assert_eq!(inject_double_dash_for_targets(args.clone(), &mut cmd), args);
    }

    #[test]
    fn try_parse_respects_existing_double_dash() {
        let cli = parse(&["kam", "-S", "--", "module"]);

        assert!(cli.sync_flag);
        assert_eq!(cli.targets, vec!["module"]);
    }

    #[test]
    fn try_parse_accepts_combined_sync_update_yes_flags() {
        let cli = parse(&["kam", "-Syu", "module"]);

        assert!(cli.sync_flag);
        assert!(cli.update_index);
        assert!(cli.assume_yes);
        assert_eq!(cli.targets, vec!["module"]);
    }

    #[test]
    fn try_parse_accepts_explicit_search_combo() {
        let cli = parse(&["kam", "-Ss", "term"]);

        assert!(cli.sync_flag);
        assert!(cli.search_flag);
        assert_eq!(cli.targets, vec!["term"]);
    }

    #[test]
    fn parse_from_with_pacman_returns_cli_on_success() {
        let cli = Cli::parse_from_with_pacman(["kam", "--quiet", "build"]);

        assert!(cli.quiet);
        assert!(matches!(cli.command, Some(Commands::Build(_))));
    }

    #[test]
    fn parses_every_top_level_subcommand_variant() {
        type CommandCase<'a> = (&'a [&'a str], fn(&Commands) -> bool);

        let cases: &[CommandCase<'_>] = &[
            (&["kam", "init", "demo"], |cmd| {
                matches!(cmd, Commands::Init(_))
            }),
            (&["kam", "build"], |cmd| matches!(cmd, Commands::Build(_))),
            (&["kam", "version"], |cmd| {
                matches!(cmd, Commands::Version(_))
            }),
            (&["kam", "cache", "list"], |cmd| {
                matches!(cmd, Commands::Cache(_))
            }),
            (&["kam", "tmpl", "list"], |cmd| {
                matches!(cmd, Commands::Tmpl(_))
            }),
            (&["kam", "validate"], |cmd| {
                matches!(cmd, Commands::Validate(_))
            }),
            (&["kam", "completions", "bash"], |cmd| {
                matches!(cmd, Commands::Completions(_))
            }),
            (&["kam", "secret", "list"], |cmd| {
                matches!(cmd, Commands::Secret(_))
            }),
            (&["kam", "sign", "module.zip"], |cmd| {
                matches!(cmd, Commands::Sign(_))
            }),
            (&["kam", "verify", "module.zip"], |cmd| {
                matches!(cmd, Commands::Verify(_))
            }),
            (&["kam", "check"], |cmd| matches!(cmd, Commands::Check(_))),
            (&["kam", "export", "prop"], |cmd| {
                matches!(cmd, Commands::Export(_))
            }),
            (&["kam", "toml", "list"], |cmd| {
                matches!(cmd, Commands::Toml(_))
            }),
            (&["kam", "config", "list"], |cmd| {
                matches!(cmd, Commands::Config(_))
            }),
            (&["kam", "install", "module.zip"], |cmd| {
                matches!(cmd, Commands::Install(_))
            }),
            (&["kam", "repo", "sync"], |cmd| {
                matches!(cmd, Commands::Repo(_))
            }),
            (&["kam", "about"], |cmd| matches!(cmd, Commands::About(_))),
            (&["kam", "env"], |cmd| matches!(cmd, Commands::Env(_))),
            (&["kam", "help"], |cmd| matches!(cmd, Commands::Help(_))),
        ];

        for (args, is_expected_variant) in cases {
            let cli = parse(args);
            let command = cli.command.expect("subcommand should be present");
            assert!(
                is_expected_variant(&command),
                "unexpected command variant for args: {args:?}"
            );
        }
    }

    #[test]
    fn parses_kernel_su_secret_subcommands() {
        let generated = parse(&["kam", "secret", "ksu-generate", "--no-gpg"]);
        let Some(Commands::Secret(secret)) = generated.command else {
            panic!("expected secret command");
        };
        assert!(matches!(
            secret.command,
            Some(SecretCommands::KsuGenerate { no_gpg: true, .. })
        ));

        let submit = parse(&[
            "kam",
            "secret",
            "ksu-submit",
            "--username",
            "octo",
            "--public-key",
            "key.pem",
        ]);
        let Some(Commands::Secret(secret)) = submit.command else {
            panic!("expected secret command");
        };
        assert!(matches!(
            secret.command,
            Some(SecretCommands::KsuSubmit { username, .. }) if username == "octo"
        ));

        let revoke = parse(&[
            "kam",
            "secret",
            "ksu-revoke",
            "--username",
            "octo",
            "--serial-number",
            "01ab",
            "--reason",
            "lost",
        ]);
        let Some(Commands::Secret(secret)) = revoke.command else {
            panic!("expected secret command");
        };
        assert!(matches!(
            secret.command,
            Some(SecretCommands::KsuRevoke {
                serial_number: Some(serial),
                ..
            }) if serial == "01ab"
        ));
    }
}
