/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public module 'about'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub mod about;
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public module 'build'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub mod build;
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public module 'cache'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub mod cache;
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public module 'check'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub mod check;
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public module 'completion'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub mod completion;
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public module 'config'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub mod config;
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public module 'env'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub mod env;
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public module 'export'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub mod export;
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public module 'help'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub mod help;
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public module 'init'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub mod init;
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public module 'install'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub mod install;
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public module 'repo'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub mod repo;
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public module 'secret'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub mod secret;
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public module 'secret_crypto'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub mod secret_crypto;
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public module 'sign'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub mod sign;

/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public module 'tmpl'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub mod tmpl;
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public module 'toml'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub mod toml;
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public module 'validate'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub mod validate;
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public module 'verify'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub mod verify;
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public module 'version'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub mod version;
