// Central error aggregation module. This file defines the global `KamError`
// and re-exports commonly used error types under `crate::errors::*`.
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public module 'kam'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub mod kam;
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public module 'kam_toml'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub mod kam_toml;

pub use kam_toml::KamTomlError;
pub use kam_toml::ValidationResult;

pub use kam::KamError;
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public type 'Result'. Replace with real documentation. (2025-12-30T22:23:21Z)
pub type Result<T> = std::result::Result<T, KamError>;
