//! kam - Command-line interface for the `kam` tool.
//!
//! Entrypoint for the `kam` binary. This module builds the clap `Command` from
//! the derive-generated `Cli` struct, injects localized about/help strings
//! (top-level, subcommands and arguments) using keys from `src/i18n/{en,zh}.toml`,
//! and dispatches to the selected subcommand.
//!
//! Translated keys used:
//! - `cli.about` / `cli.long_about`
//! - `cli.flags.<arg_id>`
//! - `cli.commands.<cmd>[.<subcmd>...].summary`
//! - `cli.commands.<cmd>[.<subcmd>...].description`
//! - `cli.commands.<cmd>[.<subcmd>...].flags.<arg_id>`
//!
//! The i18n layer (`kam::i18n::tr`) returns the original key when a translation
//! is missing; in those cases the binary falls back to the static help strings
//! generated by clap.
#![warn(clippy::pedantic)]
#![warn(clippy::perf)]
#![deny(clippy::clone_on_ref_ptr)]
#![deny(clippy::unwrap_used)]
#![deny(clippy::expect_used)]
#![deny(warnings)]
#![deny(clippy::all)]
#![deny(missing_docs)]

include!("main_entry/help_i18n.rs");
include!("main_entry/cli_runtime.rs");
