use clap::Args;

// 版本命令的参数
/// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public struct 'VersionArgs'. Replace with real documentation. (2025-12-30T22:23:21Z)
#[derive(Args, Debug)]
pub struct VersionArgs {
    // 新版本号（如 1.0.1）或bump类型（major, minor, patch）
    #[arg(value_name = "VERSION")]
    /// AUTO-GENERATED BY Kam/scripts/add_missing_docs.py: placeholder documentation for public field 'version' in 'VersionArgs'. Replace with real documentation. (2025-12-30T22:23:21Z)
    pub version: Option<String>,
}
